# Generated by Django 5.2.6 on 2025-09-25 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_dtw_distance', models.FloatField(default=1000.0, help_text='점수 정규화를 위한 최대 DTW 거리')),
            ],
        ),
        migrations.CreateModel(
            name='MotionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('data_frames', models.IntegerField()),
                ('score_category', models.CharField(choices=[('reference', '모범 동작'), ('zero_score', '0점 동작')], max_length=20)),
                ('sensor_data_json', models.JSONField()),
                ('motion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='ai.motiontype')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('motion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.motiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_recordings', to='organizations.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uid', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_devices', to='organizations.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'device_uid'), name='uq_ai_sensor_device_company_uid')],
            },
        ),
    ]
