# Generated by Django 5.2.6 on 2025-09-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordevice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrecording",
            name="motion_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ai.motiontype"
            ),
        ),
        migrations.AddField(
            model_name="userrecording",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motion_recordings",
                to="organizations.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensordevice",
            constraint=models.UniqueConstraint(
                fields=("company", "device_uid"), name="uq_ai_sensor_device_company_uid"
            ),
        ),
    ]
